---
title: "Names"
author: "Alexander Clemen"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r heacd}
library(tidyverse)
```

```{r read in data}
data <- read.delim("~/02_study/duesseldorf/BA_Linguistik/09_BBA_Bachelorarbeit/02_daten/01_Norming_Study/01_Names/Names.txt")
```


```{r}
#trimming the columns to the essential
data <- data[, c(1,3)]
head(data)

#subsetting into the diverse, male, female
SexD <- filter(data, expectedSex == "d")
SexM <- filter(data, expectedSex == "m")
SexF <- filter(data, expectedSex == "f")

#lists and plots of most common names####

#This is the top 45 for diverse names
tab_SexD <- table(SexD$Name)
sort(table(SexD$Name),decreasing = T)
plot(sort(table(SexD$Name),decreasing = T))

df_SexD <- as.data.frame(tab_SexD)
df_SexD$Freq = as.numeric(df_SexD$Freq)
# df_SexD_cut <- filter(df_SexD, Freq > 4)
df_SexD_cut <- filter(df_SexD, Freq > 3) #longer list
# View(df_SexD_cut)

#This is the top 60 for male names
tab_SexM <- table(SexM$Name)
sort(table(SexM$Name),decreasing = T)
plot(sort(table(SexM$Name),decreasing = T))

df_SexM <- as.data.frame(tab_SexM)
df_SexM$Freq = as.numeric(df_SexM$Freq)
# df_SexM_cut <- filter(df_SexM, Freq > 8)
df_SexM_cut <- filter(df_SexM, Freq > 7)#longer list
# View(df_SexM_cut)

#This is the top 57 for female names
tab_SexF <- table(SexF$Name)
sort(table(SexF$Name),decreasing = T)
plot(sort(table(SexF$Name),decreasing = T))

df_SexF <- as.data.frame(tab_SexF)
df_SexF$Freq = as.numeric(df_SexF$Freq)
# df_SexF_cut <- filter(df_SexF, Freq > 6)
df_SexF_cut <- filter(df_SexF, Freq > 5)# longer list
# View(df_SexF_cut)

#modify the datasets such that their frequencies are comparable. This will help to select the right candidates later
?modify
View(df_SexD_cut) #i check for the lowest frequency and set this to 1
df_SexD_cut$Freq <- modify(df_SexD_cut$Freq, ~ .x -3)
View(df_SexD_cut)

View(df_SexF_cut) #now the same for F and M
df_SexF_cut$Freq <- modify(df_SexF_cut$Freq, ~ .x -5)
View(df_SexF_cut)

View(df_SexM_cut)
df_SexM_cut$Freq <- modify(df_SexM_cut$Freq, ~ .x -7)
View(df_SexM_cut)

#####
#add Sex.Type to the dataframes
df_SexD_cut$expectedSex <- "d"
df_SexF_cut$expectedSex <- "f"
df_SexM_cut$expectedSex <- "m"

#merging the three data sets
Norming_Study <- rbind(df_SexD_cut, df_SexF_cut, df_SexM_cut)
# View(Norming_Study)

#renaming an anoying variable name
names(Norming_Study)[names(Norming_Study) == 'Var1'] <- 'Name'
# View(Norming_Study)


#with a histogram and manually checking for "duplicates"
plot(Norming_Study$Name)
sort(Norming_Study$Name)
#### "Maria" and "Jule" is shown in "d" and "f"

write.csv(Norming_Study, 'Norming_CommonNames_Unfiltered')
```
